<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cetak Laporan Perkembangan</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
        }

        .content {
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table th,
        table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        table th {
            background-color: #f2f2f2;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Laporan Perkembangan Siswa</h1>
        <p>Nama Siswa: <strong>{{ $laporanPerkembangan->siswa->user->name }}</strong></p>
        <p>NIS: <strong>{{ $laporanPerkembangan->siswa->nis }}</strong></p>
        <p>Kelas: <strong>{{ $laporanPerkembangan->siswa->kelas }}</strong></p>
    </div>

    <div class="content">
        <h2>Detail Laporan</h2>
        <table>
            <tr>
                <th>Deskripsi</th>
                <td>{{ $laporanPerkembangan->deskripsi }}</td>
            </tr>
            <tr>
                <th>Nilai Matematika</th>
                <td>{{ $laporanPerkembangan->nilai_matematika }}</td>
            </tr>
            <tr>
                <th>Nilai IPA</th>
                <td>{{ $laporanPerkembangan->nilai_ipa }}</td>
            </tr>
            <tr>
                <th>Nilai PPKn</th>
                <td>{{ $laporanPerkembangan->nilai_ppkn }}</td>
            </tr>
            <tr>
                <th>Nilai Bahasa Indonesia</th>
                <td>{{ $laporanPerkembangan->nilai_bahasa_indonesia }}</td>
            </tr>
        </table>

        <h2>Kehadiran</h2>
        <table>
            <tr>
                <th>Jumlah Hadir</th>
                <td>{{ $laporanPerkembangan->jumlah_hadir }}</td>
            </tr>
            <tr>
                <th>Jumlah Tidak Hadir</th>
                <td>{{ $laporanPerkembangan->jumlah_tidak_hadir }}</td>
            </tr>
        </table>

        <h2>Catatan</h2>
        <p>{{ $laporanPerkembangan->catatan }}</p>

        <h2>Tanggal</h2>
        <p>{{ $laporanPerkembangan->tanggal }}</p>
    </div>

    {{-- <div class="footer">
        <p>Generated by Sistem Informasi Sekolah</p>
    </div> --}}
</body>

</html>
